version: '3'
services:

  pilot:
    build:
      context: ./
      dockerfile: Dockerfile-pilot
    networks:
      envoy-sds-network:
        ipv4_address: 172.28.0.5
        aliases:
          - pilot
    expose:
      - "15010"
    
  servicea:
    build:
      context: ./
      dockerfile: Dockerfile-service
    networks:
      envoy-sds-network:
        ipv4_address: 172.28.0.3
        aliases:
          - serviceA
    environment:
      - SERVICE_NAME=1
    expose:
      - "80"

  serviceb:
    build:
      context: ./
      dockerfile: Dockerfile-service
    networks:
      envoy-sds-network:
        ipv4_address: 172.28.0.4
        aliases:
          - serviceB
    environment:
      - SERVICE_NAME=2
    expose:
      - "80"
  
  front-envoy:
    build:
      context: ./
      dockerfile: Dockerfile-frontenvoy
    networks:
      envoy-sds-network:
        ipv4_address: 172.28.0.2
    expose:
      - "80"
      - "443"
      - "9901"
    ports:
      - "8088:80"
      - "8443:443"
      - "9901:9901"

networks:
  envoy-sds-network: 
    ipam:
        config:
        - subnet: 172.28.0.0/16
